// Class: ReadCFMlpANN
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : CFMlpANN::CFMlpANN
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : gsmith
Date           : Wed Jun 26 14:25:33 2013
Host           : Linux lxbuild167.cern.ch 2.6.18-308.1.1.el5 #1 SMP Wed Mar 7 19:25:07 CET 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/gsmith/cms_work/CMSSW_5_2_6/src/AnalysisCode/LeptonPlusJets/macros/tmva
Training events: 1782
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NCycles: "2000" [Number of training cycles]
HiddenLayers: "N,N-1" [Specification of hidden layer architecture]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
all_sum_pt_with_met           all_sum_pt_with_met           all_sum_pt_with_met           all_sum_pt_with_met           all_sum_pt_with_met               'F'    [262.309936523,1473.55383301]
avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets                'F'    [0.972157716751,3.26925873756]
avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags               'F'    [0.752647519112,0.999973833561]
dev_from_avg_disc_btags       dev_from_avg_disc_btags       dev_from_avg_disc_btags       dev_from_avg_disc_btags       dev_from_avg_disc_btags           'F'    [7.51361639573e-10,0.0217951815575]
lowest_btag                   lowest_btag                   lowest_btag                   lowest_btag                   lowest_btag                       'F'    [0.679036259651,0.999928057194]
second_highest_btag           second_highest_btag           second_highest_btag           second_highest_btag           second_highest_btag               'F'    [0.692920148373,0.999999880791]
third_highest_btag            third_highest_btag            third_highest_btag            third_highest_btag            third_highest_btag                'F'    [0.685935556889,0.999995708466]
maxeta_jet_tag                maxeta_jet_tag                maxeta_jet_tag                maxeta_jet_tag                maxeta_jet_tag                    'F'    [0.276362448931,3.88770914078]
pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets       'F'    [0.260173112154,0.966796278954]
ttbb_tth_MVA_output_5j4t      ttbb_tth_MVA_output_5j4t      ttbb_tth_MVA_output_5j4t      ttbb_tth_MVA_output_5j4t      ttbb_tth_MVA_output_5j4t          'F'    [-0.893193662167,0.707040965557]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadCFMlpANN : public IClassifierReader {

 public:

   // constructor
   ReadCFMlpANN( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadCFMlpANN" ),
        fNvars( 10 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "all_sum_pt_with_met", "avg_dr_tagged_jets", "avg_btag_disc_btags", "dev_from_avg_disc_btags", "lowest_btag", "second_highest_btag", "third_highest_btag", "maxeta_jet_tag", "pt_all_jets_over_E_all_jets", "ttbb_tth_MVA_output_5j4t" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 262.309936523438;
      fVmax[0] = 1473.55383300781;
      fVmin[1] = 0.972157716751099;
      fVmax[1] = 3.26925873756409;
      fVmin[2] = 0.752647519111633;
      fVmax[2] = 0.999973833560944;
      fVmin[3] = 7.51361639572679e-10;
      fVmax[3] = 0.0217951815575361;
      fVmin[4] = 0.679036259651184;
      fVmax[4] = 0.999928057193756;
      fVmin[5] = 0.69292014837265;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = 0.68593555688858;
      fVmax[6] = 0.999995708465576;
      fVmin[7] = 0.27636244893074;
      fVmax[7] = 3.88770914077759;
      fVmin[8] = 0.260173112154007;
      fVmax[8] = 0.966796278953552;
      fVmin[9] = -0.893193662166595;
      fVmax[9] = 0.707040965557098;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadCFMlpANN() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // not implemented for class: "ReadCFMlpANN"
};
   inline double ReadCFMlpANN::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
