// Class: ReadCFMlpANN
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : CFMlpANN::CFMlpANN
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.32/00       [335872]
Creator        : gsmith
Date           : Sun Jun 23 14:15:05 2013
Host           : Linux lxbuild167.cern.ch 2.6.18-308.1.1.el5 #1 SMP Wed Mar 7 19:25:07 CET 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/gsmith/cms_work/CMSSW_5_2_6/src/AnalysisCode/LeptonPlusJets/macros/tmva
Training events: 9692
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NCycles: "2000" [Number of training cycles]
HiddenLayers: "N,N-1" [Specification of hidden layer architecture]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
h0                            h0                            h0                            h0                            h0                                'F'    [0.198397666216,0.436662733555]
all_sum_pt_with_met           all_sum_pt_with_met           all_sum_pt_with_met           all_sum_pt_with_met           all_sum_pt_with_met               'F'    [301.096862793,2186.82250977]
sphericity                    sphericity                    sphericity                    sphericity                    sphericity                        'F'    [0.0214823912829,0.933876872063]
avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags               'F'    [0.708269953728,0.99999153614]
second_highest_btag           second_highest_btag           second_highest_btag           second_highest_btag           second_highest_btag               'F'    [0.683702290058,0.999999880791]
third_highest_btag            third_highest_btag            third_highest_btag            third_highest_btag            third_highest_btag                'F'    [0.679063618183,0.999985694885]
fourth_highest_btag           fourth_highest_btag           fourth_highest_btag           fourth_highest_btag           fourth_highest_btag               'F'    [-1,0.678716719151]
maxeta_jet_jet                maxeta_jet_jet                maxeta_jet_jet                maxeta_jet_jet                maxeta_jet_jet                    'F'    [0.344052791595,4.38394451141]
pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets       'F'    [0.218563511968,0.970315158367]
ttbb_tth_MVA_output_6j3t      ttbb_tth_MVA_output_6j3t      ttbb_tth_MVA_output_6j3t      ttbb_tth_MVA_output_6j3t      ttbb_tth_MVA_output_6j3t          'F'    [-0.839958131313,0.494376987219]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadCFMlpANN : public IClassifierReader {

 public:

   // constructor
   ReadCFMlpANN( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadCFMlpANN" ),
        fNvars( 10 ),
        fIsNormalised( true )
   {      
      // the training input variables
      const char* inputVars[] = { "h0", "all_sum_pt_with_met", "sphericity", "avg_btag_disc_btags", "second_highest_btag", "third_highest_btag", "fourth_highest_btag", "maxeta_jet_jet", "pt_all_jets_over_E_all_jets", "ttbb_tth_MVA_output_6j3t" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0.198397666215897;
      fVmax[0] = 0.43666273355484;
      fVmin[1] = 301.096862792969;
      fVmax[1] = 2186.82250976562;
      fVmin[2] = 0.0214823912829161;
      fVmax[2] = 0.933876872062683;
      fVmin[3] = 0.708269953727722;
      fVmax[3] = 0.999991536140442;
      fVmin[4] = 0.683702290058136;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = 0.679063618183136;
      fVmax[5] = 0.999985694885254;
      fVmin[6] = -1;
      fVmax[6] = 0.678716719150543;
      fVmin[7] = 0.344052791595459;
      fVmax[7] = 4.38394451141357;
      fVmin[8] = 0.218563511967659;
      fVmax[8] = 0.970315158367157;
      fVmin[9] = -0.839958131313324;
      fVmax[9] = 0.494376987218857;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadCFMlpANN() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // not implemented for class: "ReadCFMlpANN"
};
   inline double ReadCFMlpANN::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
