// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/05       [393733]
Creator        : flowers1
Date           : Tue Sep 15 13:43:37 2015
Host           : Linux cmsbuild32.cern.ch 2.6.32-504.8.1.el6.x86_64 #1 SMP Wed Jan 28 08:50:46 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /uscms_data/d3/flowers1/May2015/CMSSW_7_4_4_patch4/src/ttH-LeptonPlusJets/AnalysisCode/macros/TRAINHOUSE74X
Training events: 2364
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "150" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "5.000000e-02" [Learning rate for GradBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
NegWeightTreatment: "ignorenegweightsintraining" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
h1                            h1                            h1                            h1                            h1                                'F'    [-0.194163948298,0.321733623743]
avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets                'F'    [0.902817070484,3.49610733986]
sphericity                    sphericity                    sphericity                    sphericity                    sphericity                        'F'    [0.0298742167652,0.8951638937]
avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags               'F'    [0.906515061855,22.9995384216]
h2                            h2                            h2                            h2                            h2                                'F'    [-0.133237406611,0.288369178772]
closest_tagged_dijet_mass     closest_tagged_dijet_mass     closest_tagged_dijet_mass     closest_tagged_dijet_mass     closest_tagged_dijet_mass         'F'    [18.9193611145,328.142883301]
second_highest_btag           second_highest_btag           second_highest_btag           second_highest_btag           second_highest_btag               'F'    [0.89450186491,1]
fourth_highest_btag           fourth_highest_btag           fourth_highest_btag           fourth_highest_btag           fourth_highest_btag               'F'    [0.890012145042,0.998860955238]
maxeta_jet_jet                maxeta_jet_jet                maxeta_jet_jet                maxeta_jet_jet                maxeta_jet_jet                    'F'    [0.0176617205143,1.54658257961]
pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets       'F'    [0.243799209595,0.98329693079]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "h1", "avg_dr_tagged_jets", "sphericity", "avg_btag_disc_btags", "h2", "closest_tagged_dijet_mass", "second_highest_btag", "fourth_highest_btag", "maxeta_jet_jet", "pt_all_jets_over_E_all_jets" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469739,-0.00217147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.724137,0.0214964) , 
3, 0.97069, 1, 0, 0.575874,0.0758738) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.181107,-0.0177988) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493186,-0.000500604) , 
7, 0.945958, 1, 0, 0.247318,-0.252682) , 
1, 2.4438, 1, 0, 0.517061,0.0170611)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43223,-0.00461393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.13243,-0.0193863) , 
1, 2.35054, 1, 0, 0.338606,-0.158364) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50162,0.000115136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.739684,0.0226261) , 
3, 0.972709, 1, 0, 0.640809,0.13569) , 
3, 0.962133, 1, 0, 0.509923,0.00833324)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441687,-0.00411848) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.126,-0.019238) , 
1, 2.55401, 1, 0, 0.405351,-0.0934882) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.850006,0.0378104) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421909,-0.00605861) , 
1, 2.38867, 1, 0, 0.765983,0.246241) , 
3, 0.977421, 1, 0, 0.491789,-0.0120604)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29649,-0.0119426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495859,0.000655108) , 
5, 100.941, 1, 0, 0.344335,-0.145962) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670764,0.0137279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320125,-0.0109038) , 
1, 2.50819, 1, 0, 0.620156,0.105639) , 
3, 0.962071, 1, 0, 0.496634,-0.00703684)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413973,-0.00537713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.132257,-0.0185413) , 
1, 2.377, 1, 0, 0.331319,-0.156713) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.799752,0.0286241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532591,0.00139259) , 
1, 2.27037, 1, 0, 0.708108,0.181888) , 
3, 0.968094, 1, 0, 0.492319,-0.0120306)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.280184,-0.0122107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521774,0.0027506) , 
0, 0.169969, 1, 0, 0.304943,-0.177323) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.709875,0.0169384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2659,-0.0133684) , 
1, 2.40543, 1, 0, 0.609335,0.0877251) , 
3, 0.958961, 1, 0, 0.492624,-0.0139003)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.122049,-0.0188522) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33796,-0.00889586) , 
3, 0.936643, 1, 0, 0.293462,-0.183486) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697205,0.0143072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453413,-0.00380434) , 
1, 2.25695, 1, 0, 0.61859,0.0863256) , 
3, 0.959297, 1, 0, 0.488068,-0.0219898)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.283659,-0.0113837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.704029,0.0203175) , 
0, 0.214045, 1, 0, 0.319883,-0.152185) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659855,0.0108714) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244924,-0.0164261) , 
5, 155.482, 1, 0, 0.63431,0.09729) , 
3, 0.962071, 1, 0, 0.501731,-0.00790195)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400086,-0.0053583) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.146768,-0.0165971) , 
1, 2.38572, 1, 0, 0.331504,-0.13976) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581268,0.00363454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.820234,0.0281997) , 
7, 0.956358, 1, 0, 0.646529,0.101047) , 
3, 0.963569, 1, 0, 0.494298,-0.0153196)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465625,-0.00417498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.662247,0.0122003) , 
5, 76.0444, 1, 0, 0.546098,0.0215485) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0666081,-0.0192874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339724,-0.00959732) , 
3, 0.961865, 1, 0, 0.189653,-0.271114) , 
1, 2.47157, 1, 0, 0.486409,-0.0274599)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456506,-0.00375728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19021,-0.0152225) , 
1, 2.38747, 1, 0, 0.393907,-0.10315) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.776199,0.0228171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38065,-0.00990065) , 
8, 0.970452, 1, 0, 0.693569,0.140721) , 
6, 0.995367, 1, 0, 0.466779,-0.0438451)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2382,-0.0130579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465739,0.000316304) , 
5, 90.3873, 1, 0, 0.304486,-0.155926) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741128,0.0180131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251712,-0.0134425) , 
1, 2.46521, 1, 0, 0.636853,0.093609) , 
3, 0.95933, 1, 0, 0.511307,-0.000648564)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462448,-0.00249876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.728899,0.0141719) , 
7, 0.931173, 1, 0, 0.567078,0.034709) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.175643,-0.0157997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51014,0.00123843) , 
2, 0.41015, 1, 0, 0.255473,-0.209227) , 
1, 2.35361, 1, 0, 0.480545,-0.0330324)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378184,-0.00498782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.189329,-0.0149933) , 
4, 0.0587633, 1, 0, 0.301419,-0.151651) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678132,0.0110719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357891,-0.0073225) , 
1, 2.3847, 1, 0, 0.597063,0.0611481) , 
3, 0.954181, 1, 0, 0.52084,0.00628369)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.186616,-0.0149141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411607,-0.00332641) , 
9, 0.602522, 1, 0, 0.317831,-0.137354) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591221,0.00346408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.781089,0.0214213) , 
6, 0.996319, 1, 0, 0.658531,0.0977567) , 
3, 0.962435, 1, 0, 0.512423,-0.00306974)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.268087,-0.0113592) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.543245,0.00627877) , 
7, 0.922654, 1, 0, 0.311835,-0.144879) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619986,0.00435249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.923087,0.0452819) , 
0, 0.191722, 1, 0, 0.646998,0.0758319) , 
3, 0.963585, 1, 0, 0.480169,-0.0340282)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.334157,-0.00920049) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545883,0.00288248) , 
9, 0.671137, 1, 0, 0.427192,-0.063883) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.8525,0.0308393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.700838,0.008446) , 
6, 0.997506, 1, 0, 0.784778,0.179656) , 
3, 0.976891, 1, 0, 0.513122,-0.00535875)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.352842,-0.00662125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628929,0.00359353) , 
3, 0.962435, 1, 0, 0.512582,-0.0193314) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393476,-0.00387358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139552,-0.0159459) , 
1, 2.56002, 1, 0, 0.201159,-0.229958) , 
1, 2.50819, 1, 0, 0.464182,-0.0520662)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488116,-0.000624731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304831,-0.0094654) , 
1, 2.11871, 1, 0, 0.398433,-0.0774302) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557914,-0.000196085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.845465,0.0282306) , 
6, 0.994671, 1, 0, 0.673329,0.0922847) , 
7, 0.93099, 1, 0, 0.517286,-0.00405277)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.694245,0.0213177) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263855,-0.0107819) , 
4, -0.0769946, 1, 0, 0.28829,-0.154015) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713859,0.012134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415587,-0.00956847) , 
8, 0.900116, 1, 0, 0.632605,0.0523076) , 
3, 0.963147, 1, 0, 0.471254,-0.0443777)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48623,-0.000664242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.164403,-0.0142068) , 
1, 2.48562, 1, 0, 0.428061,-0.0521796) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.671871,0.00732705) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.887356,0.0332059) , 
6, 0.995475, 1, 0, 0.755739,0.144876) , 
7, 0.941487, 1, 0, 0.520898,0.00365004)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517159,-0.00183831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.767421,0.0218351) , 
5, 92.9493, 1, 0, 0.589179,0.0428135) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266483,-0.011275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.73384,0.022119) , 
2, 0.529623, 1, 0, 0.312887,-0.142567) , 
1, 2.35996, 1, 0, 0.517649,-0.0051801)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25225,-0.0112411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440639,-0.000325993) , 
5, 99.5046, 1, 0, 0.297041,-0.142668) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536956,-0.0026227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.766587,0.0160727) , 
6, 0.994659, 1, 0, 0.638553,0.0466554) , 
3, 0.963504, 1, 0, 0.48171,-0.0402932)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.235319,-0.0117769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609703,0.00494487) , 
6, 0.951836, 1, 0, 0.568958,0.0294384) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.136989,-0.0160431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352138,-0.0048973) , 
5, 96.1747, 1, 0, 0.247119,-0.175957) , 
1, 2.46448, 1, 0, 0.507069,-0.0100585)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.248923,-0.0104437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588507,0.0115881) , 
9, 0.782005, 1, 0, 0.325464,-0.101122) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586076,9.70073e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.830451,0.0276232) , 
0, 0.138579, 1, 0, 0.625739,0.0394768) , 
3, 0.959297, 1, 0, 0.507146,-0.0160527)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0609217,-0.0182496) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474964,-0.0041041) , 
3, 0.937832, 1, 0, 0.434366,-0.0830852) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534172,0.00160564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.802161,0.0274469) , 
0, 0.0765511, 1, 0, 0.600913,0.0756816) , 
5, 92.544, 1, 0, 0.49234,-0.0278192)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304094,-0.0097754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.485836,0.00177824) , 
5, 101.064, 1, 0, 0.348422,-0.110778) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.811508,0.0198224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475016,-0.00368285) , 
1, 2.3847, 1, 0, 0.753864,0.129745) , 
3, 0.970779, 1, 0, 0.496598,-0.0228745)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521357,-0.00197095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.804255,0.0238685) , 
5, 103.187, 1, 0, 0.581797,0.0243486) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.193726,-0.0133652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459889,-0.00189804) , 
2, 0.404126, 1, 0, 0.27535,-0.163644) , 
1, 2.35675, 1, 0, 0.504616,-0.0229992)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.211468,-0.0116035) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408034,-0.00193884) , 
5, 97.9585, 1, 0, 0.269563,-0.144993) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686471,0.00739888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293232,-0.0096347) , 
1, 2.4708, 1, 0, 0.618939,0.0366526) , 
3, 0.959297, 1, 0, 0.481905,-0.0345934)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.206031,-0.0123963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.639264,0.00576524) , 
3, 0.945927, 1, 0, 0.577255,0.0243049) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210389,-0.0123548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497773,0.00213624) , 
2, 0.399913, 1, 0, 0.282811,-0.145985) , 
1, 2.3847, 1, 0, 0.505327,-0.0172939)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366598,-0.00744475) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.728823,0.00808599) , 
3, 0.978231, 1, 0, 0.436811,-0.0739562) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475282,-0.00352562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.709745,0.0144832) , 
2, 0.374673, 1, 0, 0.585483,0.0448942) , 
5, 94.5317, 1, 0, 0.484828,-0.035571)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.118338,-0.0153354) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570738,0.00107407) , 
3, 0.934828, 1, 0, 0.539748,-0.00676052) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.139552,-0.0155684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.283899,-0.00680557) , 
0, -0.0556671, 1, 0, 0.187123,-0.217313) , 
1, 2.44639, 1, 0, 0.471896,-0.0472749)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.15269,-0.0137586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366376,-0.00399345) , 
5, 86.1155, 1, 0, 0.222789,-0.178302) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.34001,-0.00779943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609188,0.00294603) , 
7, 0.905578, 1, 0, 0.550367,0.000305382) , 
6, 0.962688, 1, 0, 0.488103,-0.0336435)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.331389,-0.00677811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0684175,-0.0153832) , 
1, 2.47664, 1, 0, 0.270034,-0.142154) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684018,0.00678396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244924,-0.0119963) , 
1, 2.59549, 1, 0, 0.642036,0.0440195) , 
3, 0.961935, 1, 0, 0.484628,-0.0347574)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.284954,-0.00700728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0475311,-0.0181592) , 
8, 0.76266, 1, 0, 0.199951,-0.190322) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578612,0.00191974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209732,-0.0108842) , 
1, 2.60919, 1, 0, 0.54779,0.00585006) , 
6, 0.954224, 1, 0, 0.501748,-0.0201167)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.244924,-0.016361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.539771,-0.000429061) , 
5, 33.9701, 1, 0, 0.521375,-0.0215664) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.197885,-0.0123433) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382431,0.000752337) , 
0, 0.0395871, 1, 0, 0.228799,-0.168254) , 
1, 2.45969, 1, 0, 0.47254,-0.0460508)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.346115,-0.00698257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.638469,0.013614) , 
0, 0.217724, 1, 0, 0.368017,-0.0844667) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724148,0.0103481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482927,-0.00597269) , 
8, 0.737494, 1, 0, 0.623205,0.0252902) , 
7, 0.925868, 1, 0, 0.481958,-0.0354603)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43994,-0.00653194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.605734,0.00468938) , 
1, 1.95597, 1, 0, 0.554049,0.0087226) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.125189,-0.0140416) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.29784,-0.00538475) , 
5, 91.5611, 1, 0, 0.226764,-0.144578) , 
1, 2.48264, 1, 0, 0.499822,-0.0166774)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376959,-0.00708171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518764,0.000522508) , 
0, -0.0235955, 1, 0, 0.454922,-0.0421154) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.86498,0.025836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584304,-0.00489263) , 
5, 125.967, 1, 0, 0.81,0.144281) , 
7, 0.961722, 1, 0, 0.500316,-0.018286)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412441,-0.00387002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.133605,-0.0130436) , 
1, 2.3797, 1, 0, 0.344335,-0.094476) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619478,0.0025626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.963335,0.045328) , 
7, 0.984075, 1, 0, 0.650142,0.0495668) , 
7, 0.921112, 1, 0, 0.501764,-0.0203232)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40944,-0.00289444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.698928,0.00766798) , 
7, 0.926512, 1, 0, 0.534787,0.00917927) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439059,-0.00574488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0703609,-0.0157514) , 
1, 2.64714, 1, 0, 0.378441,-0.109509) , 
8, 0.792199, 1, 0, 0.482552,-0.0304738)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2525,-0.00877287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447796,0.00262905) , 
2, 0.563239, 1, 0, 0.288247,-0.107302) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316653,-0.0113783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.651063,0.0044789) , 
6, 0.974254, 1, 0, 0.622079,0.0283495) , 
3, 0.95933, 1, 0, 0.488187,-0.0260572)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611672,0.005742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445181,-0.0119208) , 
2, 0.724193, 1, 0, 0.595662,0.0441586) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332902,-0.00733176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.827606,0.0211525) , 
7, 0.961246, 1, 0, 0.396991,-0.0712427) , 
1, 2.21335, 1, 0, 0.518978,-0.00038462)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266354,-0.00835596) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454172,0.00077834) , 
7, 0.905045, 1, 0, 0.366179,-0.0550363) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617624,0.00294327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.865275,0.0248937) , 
3, 0.978409, 1, 0, 0.732759,0.10115) , 
3, 0.968094, 1, 0, 0.523902,0.0121639)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560865,0.00352764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.837024,0.0315593) , 
5, 69.6604, 1, 0, 0.69966,0.152872) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462301,-0.00379852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.746948,0.0222552) , 
0, 0.215476, 1, 0, 0.484681,-0.0285214) , 
8, 0.341615, 1, 0, 0.512027,-0.00544752)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393476,-0.0061015) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.561841,0.00456197) , 
5, 99.2008, 1, 0, 0.443767,-0.0438992) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652069,-0.00214014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.884027,0.026325) , 
0, -0.0846811, 1, 0, 0.820767,0.123434) , 
3, 0.982816, 1, 0, 0.505012,-0.0167153)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.315229,-0.00794805) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.798278,0.01538) , 
7, 0.950396, 1, 0, 0.385925,-0.0821322) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.372914,-0.010342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.665133,0.0100598) , 
8, 0.24907, 1, 0, 0.634135,0.0778648) , 
9, 0.667932, 1, 0, 0.496154,-0.0110786)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506925,-0.00215779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188109,-0.0117254) , 
1, 2.39854, 1, 0, 0.450258,-0.0553671) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704973,0.015682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463803,-0.00319328) , 
5, 129.603, 1, 0, 0.614042,0.081588) , 
5, 101.064, 1, 0, 0.49483,-0.0180959)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708337,0.0130566) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496018,-0.00243286) , 
8, 0.551884, 1, 0, 0.573616,0.0274815) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.301916,-0.0110745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608048,0.00582428) , 
0, 0.131595, 1, 0, 0.395526,-0.0949764) , 
4, 0.0541561, 1, 0, 0.512344,-0.0146505)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511224,-0.00155138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.296827,-0.01123) , 
1, 2.18659, 1, 0, 0.438084,-0.069083) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501383,-0.00217977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666698,0.00900331) , 
0, 5.32475e-05, 1, 0, 0.574105,0.0251684) , 
5, 74.412, 1, 0, 0.504038,-0.0233821)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421759,-0.00525283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546445,0.00283811) , 
5, 81.7407, 1, 0, 0.472679,-0.0284327) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.926742,0.0356254) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.819533,0.0106378) , 
6, 0.997459, 1, 0, 0.872743,0.149122) , 
7, 0.967188, 1, 0, 0.510354,-0.0117116)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362905,-0.0101167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545902,0.000382692) , 
5, 39.806, 1, 0, 0.52364,-0.0136087) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0975733,-0.014884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276208,-0.0052772) , 
9, 0.503346, 1, 0, 0.167436,-0.181171) , 
1, 2.60919, 1, 0, 0.487325,-0.0306917)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498493,-0.00134823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136989,-0.0120546) , 
1, 2.5395, 1, 0, 0.460564,-0.0353743) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.932119,0.0334621) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.739464,0.00364102) , 
5, 108.818, 1, 0, 0.882448,0.152074) , 
7, 0.967224, 1, 0, 0.503982,-0.016083)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489281,-0.00380095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.699592,0.00990352) , 
5, 82.3762, 1, 0, 0.560679,0.000804314) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.21978,-0.0123213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391663,-0.00326744) , 
0, -0.0699472, 1, 0, 0.310348,-0.114496) , 
1, 2.2766, 1, 0, 0.473066,-0.0395493)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5356,-0.000627514) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.69656,0.0116066) , 
5, 106.833, 1, 0, 0.576449,0.0228971) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3536,-0.00754517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609532,0.00616533) , 
0, 0.224539, 1, 0, 0.400517,-0.0728391) , 
4, 0.0361637, 1, 0, 0.506369,-0.0152382)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.346078,-0.00842863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.592025,0.00237963) , 
9, 0.793559, 1, 0, 0.42594,-0.0714217) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40856,-0.0027048) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.845723,0.0213527) , 
3, 0.968538, 1, 0, 0.590062,0.0437628) , 
0, 0.0824194, 1, 0, 0.469636,-0.0407549)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600086,0.00304168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403825,-0.00594426) , 
1, 2.21142, 1, 0, 0.529935,-0.00648785) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40326,-0.00601902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.150331,-0.0163709) , 
8, 0.617094, 1, 0, 0.279003,-0.173985) , 
4, 0.12223, 1, 0, 0.494365,-0.0302309)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.377308,-0.00820393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56474,0.000980625) , 
9, 0.767755, 1, 0, 0.429399,-0.0783796) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.355854,-0.00420869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.771347,0.0149112) , 
3, 0.963308, 1, 0, 0.573535,0.0375803) , 
5, 92.988, 1, 0, 0.475903,-0.0409662)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.252107,-0.008356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59658,0.00169289) , 
6, 0.954224, 1, 0, 0.54631,-0.00304493) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.254059,-0.00368491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198016,-0.0114855) , 
2, 0.187123, 1, 0, 0.211632,-0.146199) , 
1, 2.4521, 1, 0, 0.482371,-0.030394)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583555,0.00486326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38844,-0.00546728) , 
4, -0.0317405, 1, 0, 0.438111,-0.0414959) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.801907,0.0178461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548815,-0.0166124) , 
2, 0.703151, 1, 0, 0.770729,0.106886) , 
6, 0.995623, 1, 0, 0.515886,-0.00680011)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59344,0.00514167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446114,-0.00395603) , 
8, 0.731586, 1, 0, 0.534532,0.0135874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0780166,-0.0159594) , 
1, 2.85473, 1, 0, 0.514113,0.000857101)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.303683,-0.00884333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577094,0.00214935) , 
9, 0.654512, 1, 0, 0.472137,-0.032656) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528268,0.00219069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.9698,0.0453893) , 
7, 0.941918, 1, 0, 0.647963,0.0862333) , 
0, 0.11827, 1, 0, 0.509992,-0.0070595)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429489,-0.00425022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.301916,-0.0181613) , 
2, 0.625817, 1, 0, 0.420185,-0.0693477) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538688,0.000381221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.771936,0.0178033) , 
5, 74.1886, 1, 0, 0.645574,0.0715984) , 
9, 0.702906, 1, 0, 0.506655,-0.015274)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295662,-0.0166859) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.244924,-0.0154369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5496,0.00242587) , 
5, 32.7712, 1, 0, 0.537511,0.017104) , 
8, 0.209007, 1, 0, 0.527054,0.00535389)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.348623,-0.00025343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166397,-0.0118474) , 
0, -0.00324403, 1, 0, 0.238602,-0.1183) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.393476,-0.0194163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571326,0.00188173) , 
4, -0.0940205, 1, 0, 0.562065,0.00745688) , 
3, 0.945927, 1, 0, 0.516694,-0.0101825)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362553,-0.00936176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492441,-0.000680111) , 
5, 50.5729, 1, 0, 0.46568,-0.0345179) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.0521736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.886168,0.0192976) , 
0, -0.016844, 1, 0, 0.937823,0.17545) , 
7, 0.977519, 1, 0, 0.491508,-0.0230319)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326283,-0.00814144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517149,-0.00170308) , 
0, 0.0359586, 1, 0, 0.422991,-0.0671164) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.350909,-0.012914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.70287,0.0124923) , 
1, 1.73232, 1, 0, 0.661285,0.0863841) , 
9, 0.772012, 1, 0, 0.486217,-0.0263888)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.188109,-0.0155429) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453397,-0.00404664) , 
2, 0.158298, 1, 0, 0.430651,-0.0680505) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.900817,0.0418691) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584304,0.00323815) , 
8, 0.347005, 1, 0, 0.61731,0.0632839) , 
5, 92.544, 1, 0, 0.491254,-0.02541)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341669,-0.00671582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567951,0.00875352) , 
0, 0.193546, 1, 0, 0.367465,-0.0731059) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.737243,0.00486177) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.89752,0.0349503) , 
4, 0.0837241, 1, 0, 0.763093,0.0727428) , 
3, 0.97299, 1, 0, 0.494055,-0.0264384)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.258514,-0.00664409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504056,0.0050749) , 
9, 0.852152, 1, 0, 0.291015,-0.0769139) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47757,-0.0129296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.622697,0.00153722) , 
8, 0.267095, 1, 0, 0.614025,0.00554138) , 
3, 0.95933, 1, 0, 0.486959,-0.026895)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.166397,-0.019168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422129,-0.00565373) , 
5, 41.8164, 1, 0, 0.389445,-0.105124) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.244924,-0.0134112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584304,0.00432168) , 
5, 35.3146, 1, 0, 0.55319,0.023807) , 
0, -0.035585, 1, 0, 0.482067,-0.0321945)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.160844,-0.0105489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343824,-0.00201287) , 
5, 79.0676, 1, 0, 0.222145,-0.119693) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591527,0.0031894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.104563,-0.0141359) , 
1, 2.75153, 1, 0, 0.56296,0.0202206) , 
6, 0.962688, 1, 0, 0.495122,-0.00762867)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764356,0.0297013) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578515,0.00196752) , 
0, -0.130911, 1, 0, 0.590062,0.0369604) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59344,0.00311078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351188,-0.00861754) , 
4, -0.0392985, 1, 0, 0.406188,-0.0835867) , 
8, 0.637185, 1, 0, 0.490163,-0.0285328)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54831,0.00109963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370975,-0.0143568) , 
2, 0.722387, 1, 0, 0.536866,-0.000675478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.127374,-0.0118032) , 
1, 2.64136, 1, 0, 0.504932,-0.0142487)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433295,-0.015042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.764356,0.0226089) , 
4, -0.0961207, 1, 0, 0.671796,0.0938357) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.395807,-0.00680097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604504,0.00443196) , 
5, 92.544, 1, 0, 0.464837,-0.0452989) , 
4, -0.0570048, 1, 0, 0.495681,-0.024563)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433579,-0.00463685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.0485875) , 
3, 0.990716, 1, 0, 0.455254,-0.0493553) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.089851,-0.0198134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442246,-0.0085473) , 
2, 0.322046, 1, 0, 0.227179,-0.239635) , 
5, 152.836, 1, 0, 0.439968,-0.0621079)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401226,-0.00262178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.713729,0.00883103) , 
7, 0.915929, 1, 0, 0.583714,0.0322186) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.196838,-0.0121474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473872,-0.00344744) , 
0, -0.0825066, 1, 0, 0.412228,-0.0729033) , 
8, 0.697825, 1, 0, 0.506175,-0.0153135)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.106172,-0.0124213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475016,0.00440846) , 
9, 0.715324, 1, 0, 0.221623,-0.112459) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591786,0.00165063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216854,-0.00829247) , 
1, 2.57102, 1, 0, 0.551797,0.00361034) , 
6, 0.962688, 1, 0, 0.488849,-0.0185185)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.171909,-0.0109255) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609204,0.00346665) , 
3, 0.937672, 1, 0, 0.580825,0.0238472) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.105101,-0.0135963) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379105,0.00631995) , 
0, -0.0599296, 1, 0, 0.186477,-0.121398) , 
1, 2.50404, 1, 0, 0.515601,-0.000176011)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49466,-0.0016716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359007,-0.00738502) , 
4, 0.0432388, 1, 0, 0.438815,-0.0530036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.963335,0.0364158) , 
7, 0.97752, 1, 0, 0.46283,-0.0430512)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.198016,-0.0110074) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.543099,-0.000751436) , 
9, 0.570689, 1, 0, 0.47491,-0.0378674) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602495,0.00363821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.860394,0.0445653) , 
1, 2.24038, 1, 0, 0.637165,0.0788644) , 
0, 0.078748, 1, 0, 0.519426,-0.00584091)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332599,-0.00843315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.648356,0.0054547) , 
9, 0.854028, 1, 0, 0.410556,-0.0726001) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565855,0.0082114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.682038,-0.00470583) , 
7, 0.947032, 1, 0, 0.598139,0.0565445) , 
0, -0.036715, 1, 0, 0.526081,0.00693507)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.236423,-0.00862204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588596,0.00236732) , 
9, 0.62097, 1, 0, 0.483852,-0.017971) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578577,0.00334733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.786503,0.0226961) , 
5, 81.8563, 1, 0, 0.659925,0.0966081) , 
0, 0.0670944, 1, 0, 0.537017,0.0166259)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550642,0.00191546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363043,-0.0085501) , 
4, -0.0265818, 1, 0, 0.413156,-0.0774287) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.382631,-0.00593253) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.651929,0.00802333) , 
9, 0.539212, 1, 0, 0.561064,0.0295356) , 
5, 77.8191, 1, 0, 0.483069,-0.026869)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484086,-0.0015816) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.688925,0.0134732) , 
5, 107.655, 1, 0, 0.519134,0.00548995) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327304,-0.0206578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439875,-0.00313601) , 
4, -0.0116101, 1, 0, 0.397071,-0.126448) , 
5, 134.68, 1, 0, 0.507992,-0.00655397)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465902,-0.00300397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185043,-0.0169618) , 
4, 0.111496, 1, 0, 0.429671,-0.0641083) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234206,-0.00784221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692254,0.00943985) , 
3, 0.949958, 1, 0, 0.584995,0.0420269) , 
0, 0.0531436, 1, 0, 0.482334,-0.0281231)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59701,0.00210123) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412574,-0.00640945) , 
4, -0.0328549, 1, 0, 0.466559,-0.0512761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.795603,0.0259583) , 
0, 0.239254, 1, 0, 0.477518,-0.0423709)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333048,-0.0075475) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516107,-9.2275e-05) , 
5, 102.03, 1, 0, 0.381174,-0.0780767) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691463,0.00685059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375936,-0.0228377) , 
5, 127.186, 1, 0, 0.648574,0.0187553) , 
6, 0.994976, 1, 0, 0.451356,-0.052662)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398852,0.00252535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345841,-0.00603056) , 
0, -0.0638349, 1, 0, 0.358414,-0.0571715) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542054,-0.00258073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.750748,0.0123655) , 
0, -0.0279125, 1, 0, 0.652685,0.0415757) , 
7, 0.926034, 1, 0, 0.494332,-0.0115619)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.243284,-0.00753243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431464,0.00179299) , 
2, 0.408375, 1, 0, 0.315609,-0.0576046) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.806305,0.0259517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.651464,0.00235665) , 
2, 0.19114, 1, 0, 0.666417,0.042176) , 
3, 0.962435, 1, 0, 0.515365,-0.000787696)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.395226,-0.0067712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558623,0.00270167) , 
0, -0.0862496, 1, 0, 0.520486,0.00263596) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463803,0.00469479) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224575,-0.0130997) , 
5, 64.5307, 1, 0, 0.300489,-0.114473) , 
4, 0.11201, 1, 0, 0.480874,-0.0184503)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.222964,-0.0122816) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453091,-0.000594865) , 
5, 34.7842, 1, 0, 0.435566,-0.0208102) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362101,-0.00463159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.810763,0.0172959) , 
3, 0.963279, 1, 0, 0.736682,0.0996168) , 
6, 0.994976, 1, 0, 0.512926,0.0101288)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364917,-0.00477986) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.750246,0.00604423) , 
7, 0.94636, 1, 0, 0.448855,-0.0397308) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555964,0.00270337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.848998,0.0291199) , 
0, 0.0481404, 1, 0, 0.632396,0.0777326) , 
5, 99.5046, 1, 0, 0.497474,-0.00861567)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364036,-0.0165146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.519416,0.000339273) , 
4, -0.0933488, 1, 0, 0.511822,-0.00738325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21133,-0.0156655) , 
5, 158.804, 1, 0, 0.49661,-0.0186365)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628881,0.0051589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451724,-0.00320867) , 
4, -0.0203033, 1, 0, 0.504859,-0.0115057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374031,-0.0180036) , 
2, 0.71835, 1, 0, 0.497658,-0.0235089)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.291689,-0.00939694) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.553838,6.81572e-05) , 
0, 0.123811, 1, 0, 0.401235,-0.0731633) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597234,0.00577678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537875,-0.00569723) , 
0, 0.00806816, 1, 0, 0.576693,0.0190608) , 
9, 0.634899, 1, 0, 0.494836,-0.0239651)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.134299,-0.0111737) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502036,0.00634286) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58024,-0.00266459) , 
7, 0.921118, 1, 0, 0.54751,0.0156549) , 
3, 0.933545, 1, 0, 0.527877,0.0068768)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.188773,-0.0123506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628795,-0.00370968) , 
3, 0.973422, 1, 0, 0.320565,-0.147794) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.69245,0.0175961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499751,-0.000740894) , 
5, 54.3348, 1, 0, 0.519809,0.00959364) , 
5, 44.0201, 1, 0, 0.493454,-0.0112246)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.200415,-0.0152294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407687,-0.00275398) , 
5, 41.0437, 1, 0, 0.383437,-0.0581936) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.190876,-0.00926944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626556,0.00573959) , 
3, 0.945544, 1, 0, 0.57599,0.0358631) , 
0, -0.0372377, 1, 0, 0.498791,-0.00184654)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.225966,-0.014083) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421213,-0.00424576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.616674,0.00369443) , 
9, 0.666369, 1, 0, 0.516858,-0.00720313) , 
5, 35.964, 1, 0, 0.496958,-0.0213649)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568547,0.000363491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 1,0.0717138) , 
0, 0.0519991, 1, 0, 0.64469,0.0701863) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.29044,-0.00964186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465966,-0.00243423) , 
5, 41.6894, 1, 0, 0.444676,-0.0419259) , 
4, -0.0548035, 1, 0, 0.475838,-0.0244589)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474793,-0.0006702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.714094,0.015565) , 
9, 0.807755, 1, 0, 0.517526,0.0195505) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47468,-0.00415383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493186,-0.0268359) , 
7, 0.967801, 1, 0, 0.477238,-0.0813832) , 
2, 0.521069, 1, 0, 0.504577,-0.012892)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.335997,-0.0092552) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563199,0.0027736) , 
5, 43.9041, 1, 0, 0.524457,0.00300553) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526543,0.0185415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379008,-0.0104827) , 
7, 0.900107, 1, 0, 0.39491,-0.107784) , 
8, 0.883648, 1, 0, 0.493754,-0.0232517)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613364,0.00628306) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403678,-0.0109357) , 
2, 0.694049, 1, 0, 0.590014,0.0414518) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424734,-0.00399093) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253055,-0.0116879) , 
8, 1.10095, 1, 0, 0.382131,-0.0780603) , 
8, 0.765847, 1, 0, 0.504348,-0.00779753)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.180712,-0.00748283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.122049,-0.0133095) , 
6, 0.937756, 1, 0, 0.154934,-0.15324) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503391,0.00238287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640381,-0.00713704) , 
7, 0.946635, 1, 0, 0.540224,0.00333618) , 
3, 0.93765, 1, 0, 0.502853,-0.0118509)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447199,-0.00289469) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.939649,0.0343499) , 
7, 0.982677, 1, 0, 0.464672,-0.027635) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418012,-0.0067501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.70726,0.0150952) , 
5, 44.027, 1, 0, 0.650745,0.0959696) , 
2, 0.556678, 1, 0, 0.503493,-0.00184696)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470663,-0.00142988) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.625755,0.00635494) , 
0, 0.0301509, 1, 0, 0.534465,0.0160572) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0769879,-0.0132619) , 
1, 2.77557, 1, 0, 0.504736,0.00364745)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0864308,-0.0135234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299618,-0.00237096) , 
5, 48.6373, 1, 0, 0.254737,-0.0708414) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612334,0.00421254) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267354,-0.0139117) , 
5, 151.444, 1, 0, 0.5951,0.0319563) , 
3, 0.951003, 1, 0, 0.519515,0.00912804)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330979,-0.00668777) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.598975,0.00534538) , 
0, 0.132867, 1, 0, 0.422207,-0.0380672) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636268,0.00649817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.543245,-0.0096238) , 
5, 133.405, 1, 0, 0.626767,0.0506895) , 
9, 0.675566, 1, 0, 0.514159,0.00182991)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552093,0.00220148) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40326,-0.0181404) , 
5, 62.3857, 1, 0, 0.456387,-0.139777) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48158,-0.00101283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.645238,0.0111205) , 
5, 117.621, 1, 0, 0.50585,0.00578538) , 
4, -0.0736273, 1, 0, 0.500649,-0.00952158)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51206,-0.00537632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521904,0.0019995) , 
8, 0.50892, 1, 0, 0.51806,-0.0106501) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360663,-0.00364266) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27858,-0.0180182) , 
6, 0.994466, 1, 0, 0.323951,-0.144247) , 
8, 1.0502, 1, 0, 0.497019,-0.0251317)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.301916,-0.00421464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224942,-0.0203124) , 
6, 0.989248, 1, 0, 0.272055,-0.14766) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483338,-0.00313121) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.619613,0.00595554) , 
5, 107.287, 1, 0, 0.514934,-0.0151506) , 
2, 0.160549, 1, 0, 0.488688,-0.0294699)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407903,-0.00474809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.611106,0.00467393) , 
0, 0.124674, 1, 0, 0.456495,-0.0327608) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588305,0.00346081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.898643,0.03301) , 
5, 95.04, 1, 0, 0.66519,0.0838593) , 
9, 0.803319, 1, 0, 0.497818,-0.0096692)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483225,-0.000595329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39652,-0.00802505) , 
5, 73.9399, 1, 0, 0.455881,-0.0378709) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.819533,0.0182768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391031,-0.00350029) , 
1, 2.27671, 1, 0, 0.601368,0.0442806) , 
5, 100.683, 1, 0, 0.49637,-0.0150081)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529745,-7.14452e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278362,-0.0102986) , 
4, 0.107681, 1, 0, 0.503057,-0.0160842) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359087,-0.0032304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858255,0.0290198) , 
6, 0.971643, 1, 0, 0.714249,0.137214) , 
0, 0.190382, 1, 0, 0.52622,0.000728767)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507612,-0.000782382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229191,-0.0130622) , 
4, 0.107681, 1, 0, 0.470919,-0.0324637) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.6355,0.00195547) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.773955,0.025295) , 
4, 0.0794109, 1, 0, 0.701353,0.109943) , 
0, 0.130273, 1, 0, 0.505599,-0.0110319)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.261582,-0.00542982) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630203,0.00448761) , 
3, 0.950832, 1, 0, 0.546722,0.0178699) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266072,-0.0186831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401881,-0.00307487) , 
1, 2.14054, 1, 0, 0.368195,-0.0993496) , 
8, 0.955814, 1, 0, 0.516291,-0.00211058)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.285318,-0.00502474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.639057,0.00235378) , 
3, 0.959282, 1, 0, 0.506151,-0.0122445) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.257466,-0.0164015) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.596397,-0.00321065) , 
9, 0.683611, 1, 0, 0.38065,-0.159558) , 
5, 127.469, 1, 0, 0.493186,-0.0274631)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514278,-0.0031919) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318003,-0.0219271) , 
2, 0.629941, 1, 0, 0.479546,-0.0838141) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61859,0.0103386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491263,-0.00217053) , 
5, 55.5662, 1, 0, 0.515711,0.000178256) , 
1, 1.9481, 1, 0, 0.507086,-0.0198539)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680146,0.0159657) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539748,0.0094456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483069,-0.0028925) , 
2, 0.201361, 1, 0, 0.488955,-0.0209918) , 
1, 1.76725, 1, 0, 0.498358,-0.0126442)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.270637,-0.00499199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478908,0.00889934) , 
5, 101.359, 1, 0, 0.320901,-0.0293827) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540607,-0.00109679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.775679,0.0132865) , 
0, -0.0713312, 1, 0, 0.708977,0.0740125) , 
3, 0.962531, 1, 0, 0.546112,0.0306203)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.354061,-0.0069955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59657,0.000799756) , 
9, 0.753148, 1, 0, 0.443299,-0.0538152) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.3966,-0.00290103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.92162,0.0327465) , 
3, 0.966095, 1, 0, 0.631612,0.0645267) , 
0, 0.128354, 1, 0, 0.480829,-0.0302302)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514934,0.00448562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403678,-0.00616424) , 
5, 53.3736, 1, 0, 0.42607,-0.0516121) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49797,-0.00180868) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.831661,0.0226458) , 
5, 83.8931, 1, 0, 0.618013,0.04805) , 
9, 0.708848, 1, 0, 0.500622,-0.0129027)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.690931,0.0108668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474616,-0.00137513) , 
4, -0.0279647, 1, 0, 0.526368,0.0130604) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.230425,-0.0142955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.795603,0.0100252) , 
7, 0.938029, 1, 0, 0.401595,-0.133199) , 
2, 0.68033, 1, 0, 0.515351,0.000146084)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527302,-0.00071329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590262,0.00953425) , 
8, 0.852428, 1, 0, 0.537414,0.00883328) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.192904,-0.0130057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526543,0.00984782) , 
5, 87.7267, 1, 0, 0.32161,-0.077413) , 
8, 1.04079, 1, 0, 0.509533,-0.00230917)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419669,-0.00118099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.597234,0.0074595) , 
5, 88.1784, 1, 0, 0.481479,0.0172919) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536919,-0.0138846) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858796,0.00782081) , 
3, 0.99074, 1, 0, 0.607154,-0.104335) , 
7, 0.951478, 1, 0, 0.509649,-0.00997057)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359087,-0.0112962) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450338,-0.00363687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.634385,0.00332307) , 
9, 0.735245, 1, 0, 0.506987,-0.0191592) , 
8, 0.234158, 1, 0, 0.498443,-0.0271497)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410057,-0.0132734) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423029,-0.00294627) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.611867,0.0034722) , 
2, 0.383489, 1, 0, 0.5114,-0.00167696) , 
4, -0.0940205, 1, 0, 0.507213,-0.00867894)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612045,0.0138655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528612,-0.00208317) , 
2, 0.282985, 1, 0, 0.539667,-0.0033173) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381164,-0.00430614) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282577,-0.0187693) , 
9, 0.872492, 1, 0, 0.369386,-0.0794036) , 
4, 0.0682938, 1, 0, 0.49263,-0.0243349)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408312,-0.00519769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563307,0.00122469) , 
0, -0.073997, 1, 0, 0.516121,-0.0108232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.244924,-0.0133708) , 
8, 1.16156, 1, 0, 0.503425,-0.019446)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373568,-0.00519958) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666959,0.00814293) , 
0, 0.130273, 1, 0, 0.446824,-0.0292206) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591743,0.00158805) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.848998,0.0338178) , 
9, 0.893913, 1, 0, 0.609261,0.0343411) , 
2, 0.383489, 1, 0, 0.53021,0.00340855)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547891,0.00175213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343824,-0.00746413) , 
4, 0.122687, 1, 0, 0.516489,0.00121407) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314845,-0.0033377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314845,-0.0229073) , 
3, 0.967417, 1, 0, 0.314845,-0.183389) , 
5, 152.749, 1, 0, 0.503647,-0.0105428)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.234508,-0.0117221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50913,0.00015818) , 
5, 33.6443, 1, 0, 0.496917,-0.00619509) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721833,0.00220745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569417,-0.0306176) , 
0, 0.01061, 1, 0, 0.638704,-0.123455) , 
7, 0.972371, 1, 0, 0.510354,-0.0173081)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.271362,-0.00125783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149443,-0.0115978) , 
3, 0.941202, 1, 0, 0.218657,-0.0882268) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396915,-0.00433228) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604144,0.00285423) , 
0, -0.0872302, 1, 0, 0.553216,0.010006) , 
3, 0.945927, 1, 0, 0.512077,-0.00207314)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.248045,-0.00526142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.625588,0.00560484) , 
3, 0.945881, 1, 0, 0.559717,0.0341906) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.409829,-0.00441701) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291217,-0.0182829) , 
2, 0.59461, 1, 0, 0.392085,-0.0879634) , 
8, 0.883648, 1, 0, 0.519603,0.00495953)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479869,-0.000419755) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388243,-0.0107506) , 
9, 0.907477, 1, 0, 0.473071,-0.0156459) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.716721,-0.00569157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458977,-0.0345777) , 
6, 0.998871, 1, 0, 0.636268,-0.133397) , 
3, 0.986684, 1, 0, 0.494594,-0.0311754)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.154934,-0.00944191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505161,-0.00248495) , 
6, 0.958799, 1, 0, 0.445556,-0.0457894) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.706557,0.012413) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416438,-0.0074476) , 
0, 0.256303, 1, 0, 0.659541,0.0776228) , 
0, 0.120424, 1, 0, 0.484201,-0.0235015)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520405,-0.00159504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.902387,0.0194906) , 
3, 0.983071, 1, 0, 0.577427,-0.00142026) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.101797,-0.0118034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402874,-0.00267792) , 
3, 0.962873, 1, 0, 0.244924,-0.0998923) , 
1, 2.32025, 1, 0, 0.477806,-0.0309233)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.304541,-0.00893077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457136,-0.00194504) , 
5, 46.623, 1, 0, 0.42853,-0.0419594) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.960005,0.0420454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.673176,0.00224554) , 
1, 1.93173, 1, 0, 0.721833,0.0535707) , 
6, 0.995618, 1, 0, 0.499679,-0.0187858)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39676,-0.00346826) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400034,-0.0120234) , 
7, 0.939875, 1, 0, 0.397169,-0.0582508) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.948689,0.0429497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.819533,0.0101519) , 
6, 0.987063, 1, 0, 0.845465,0.103258) , 
7, 0.951782, 1, 0, 0.472653,-0.0310561)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371964,-0.00562315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.883589,0.0191417) , 
3, 0.983542, 1, 0, 0.426953,-0.0549182) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636396,0.00998837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620723,-0.00757814) , 
6, 0.994976, 1, 0, 0.631612,0.0474079) , 
5, 91.1528, 1, 0, 0.492907,-0.0219424)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547864,-0.000681327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.76852,0.011829) , 
5, 114.028, 1, 0, 0.583225,0.00909918) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.167591,-0.0117809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235235,-0.00255032) , 
4, 0.0189308, 1, 0, 0.213943,-0.0738419) , 
1, 2.44639, 1, 0, 0.511389,-0.00703523)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.467602,-0.00223891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.233186,-0.0130901) , 
5, 70.9893, 1, 0, 0.433387,-0.0509113) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59801,0.00520324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397428,-0.00732042) , 
5, 131.999, 1, 0, 0.560498,0.0251578) , 
5, 76.2983, 1, 0, 0.494674,-0.0142338)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.710401,0.0110531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515128,0.00061089) , 
4, -0.0351951, 1, 0, 0.560306,0.0285035) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660582,0.0112016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297498,-0.0150645) , 
5, 140.775, 1, 0, 0.390622,-0.128732) , 
5, 131.524, 1, 0, 0.538907,0.00867443)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322122,-0.00707071) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549579,-0.000834774) , 
9, 0.621634, 1, 0, 0.456644,-0.0408527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864485,0.0338598) , 
0, 0.240343, 1, 0, 0.471973,-0.0302819)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.291284,-0.00373898) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166907,-0.0146042) , 
6, 0.990754, 1, 0, 0.272342,-0.0792298) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.676504,0.00545199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.606416,-0.00667325) , 
9, 0.836928, 1, 0, 0.663303,0.0275774) , 
3, 0.962037, 1, 0, 0.48624,-0.0207947)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674245,0.0116235) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501232,-0.00170891) , 
8, 0.335455, 1, 0, 0.523831,-0.00197284) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.218206,-0.0127671) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374545,-0.00178916) , 
5, 106.016, 1, 0, 0.261083,-0.140812) , 
8, 1.04079, 1, 0, 0.488854,-0.0204551)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498741,0.000579152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.706501,0.0155358) , 
0, 0.0474481, 1, 0, 0.530776,0.0264465) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596104,0.00589352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437724,-0.0118176) , 
5, 63.3168, 1, 0, 0.487924,-0.0797988) , 
0, 0.103047, 1, 0, 0.519155,-0.00236669)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471334,-0.00263419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.591096,0.00296133) , 
0, 0.0279584, 1, 0, 0.519796,-0.00607142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225966,-0.012933) , 
4, 0.18561, 1, 0, 0.506747,-0.0141557)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375936,-0.0148372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540558,0.00189719) , 
4, -0.0914368, 1, 0, 0.533438,0.0109019) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.312298,-0.00622486) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297839,-0.0179768) , 
6, 0.994039, 1, 0, 0.306674,-0.149993) , 
8, 1.11112, 1, 0, 0.514378,-0.0026214)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
