// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/05       [393733]
Creator        : flowers1
Date           : Tue Sep 15 13:56:31 2015
Host           : Linux cmsbuild32.cern.ch 2.6.32-504.8.1.el6.x86_64 #1 SMP Wed Jan 28 08:50:46 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /uscms_data/d3/flowers1/May2015/CMSSW_7_4_4_patch4/src/ttH-LeptonPlusJets/AnalysisCode/macros/TRAINHOUSE74X
Training events: 2360
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "150" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "5.000000e-02" [Learning rate for GradBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
NegWeightTreatment: "ignorenegweightsintraining" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
h1                            h1                            h1                            h1                            h1                                'F'    [-0.192006126046,0.332033038139]
avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets            avg_dr_tagged_jets                'F'    [1.05849206448,3.36670780182]
sphericity                    sphericity                    sphericity                    sphericity                    sphericity                        'F'    [0.0170507375151,0.879575550556]
avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags           avg_btag_disc_btags               'F'    [0.912399470806,43.905128479]
h2                            h2                            h2                            h2                            h2                                'F'    [-0.135188147426,0.29021859169]
closest_tagged_dijet_mass     closest_tagged_dijet_mass     closest_tagged_dijet_mass     closest_tagged_dijet_mass     closest_tagged_dijet_mass         'F'    [20.1188430786,474.281188965]
second_highest_btag           second_highest_btag           second_highest_btag           second_highest_btag           second_highest_btag               'F'    [0.902371227741,1]
fourth_highest_btag           fourth_highest_btag           fourth_highest_btag           fourth_highest_btag           fourth_highest_btag               'F'    [0.890028595924,0.999187171459]
maxeta_jet_jet                maxeta_jet_jet                maxeta_jet_jet                maxeta_jet_jet                maxeta_jet_jet                    'F'    [0.019136570394,1.59217596054]
pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets   pt_all_jets_over_E_all_jets       'F'    [0.247809648514,0.984771430492]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "h1", "avg_dr_tagged_jets", "sphericity", "avg_btag_disc_btags", "h2", "closest_tagged_dijet_mass", "second_highest_btag", "fourth_highest_btag", "maxeta_jet_jet", "pt_all_jets_over_E_all_jets" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420315,-0.0059168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.199786,-0.018798) , 
1, 2.36731, 1, 0, 0.367875,-0.132125) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.738899,0.0242491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.409141,-0.00668356) , 
1, 2.37004, 1, 0, 0.667367,0.167367) , 
3, 0.9643, 1, 0, 0.521759,0.0217589)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345884,-0.0111462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.633445,0.0115825) , 
5, 43.901, 1, 0, 0.583322,0.0778362) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.11393,-0.0222527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416146,-0.00584487) , 
7, 0.90566, 1, 0, 0.315473,-0.178238) , 
1, 2.36461, 1, 0, 0.516848,0.0142851)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.340398,-0.0110886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.627307,0.010603) , 
6, 0.972106, 1, 0, 0.547851,0.041043) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364297,-0.00877685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.103639,-0.0225318) , 
4, 0.0681376, 1, 0, 0.222211,-0.265658) , 
1, 2.52769, 1, 0, 0.497856,-0.00604404)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.299915,-0.0130929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508642,0.000663149) , 
9, 0.811611, 1, 0, 0.342747,-0.152554) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.725069,0.0205688) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442073,-0.00485461) , 
1, 2.19808, 1, 0, 0.5997,0.086075) , 
3, 0.962228, 1, 0, 0.492189,-0.0137691)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.289431,-0.0135517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508956,0.00151261) , 
5, 97.8768, 1, 0, 0.352898,-0.138473) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.790664,0.0281312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515785,0.000651479) , 
1, 2.11642, 1, 0, 0.636211,0.118272) , 
3, 0.964483, 1, 0, 0.500001,-0.00516464)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475837,-0.00158513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.698673,0.0158553) , 
3, 0.967621, 1, 0, 0.592492,0.0754165) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448315,-0.0032884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215081,-0.0167137) , 
1, 2.42775, 1, 0, 0.288599,-0.193958) , 
1, 2.33578, 1, 0, 0.50325,-0.0036896)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407445,-0.00627556) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.104539,-0.020873) , 
1, 2.49919, 1, 0, 0.350145,-0.136007) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32071,-0.0145294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.658036,0.0118724) , 
5, 42.6021, 1, 0, 0.609128,0.0780097) , 
3, 0.966381, 1, 0, 0.479682,-0.0289612)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475198,-0.00244926) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.765129,0.0231458) , 
7, 0.936872, 1, 0, 0.583,0.0617432) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.232877,-0.015711) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.589366,0.00985976) , 
8, 1.08529, 1, 0, 0.285866,-0.190766) , 
1, 2.33873, 1, 0, 0.504719,-0.00478164)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.403058,-0.00609709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628996,0.00932144) , 
6, 0.981451, 1, 0, 0.537364,0.027407) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0402764,-0.0233521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.124065,-0.0207249) , 
7, 0.925589, 1, 0, 0.0816172,-0.379557) , 
1, 2.70722, 1, 0, 0.498936,-0.0069078)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503336,-0.000467804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.764201,0.0208245) , 
3, 0.973205, 1, 0, 0.605764,0.073161) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267225,-0.0141304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572309,0.00421334) , 
3, 0.977064, 1, 0, 0.345419,-0.146081) , 
1, 2.16469, 1, 0, 0.478684,-0.0338562)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.180821,-0.0176025) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374376,-0.00776077) , 
6, 0.958155, 1, 0, 0.323744,-0.15373) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.749381,0.0186954) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404712,-0.00730414) , 
1, 2.21556, 1, 0, 0.612617,0.068147) , 
3, 0.967335, 1, 0, 0.459257,-0.0496453)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392185,-0.00723465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.665649,0.0114507) , 
7, 0.905258, 1, 0, 0.591771,0.0611232) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.213192,-0.016011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464871,-1.94739e-05) , 
5, 108.408, 1, 0, 0.294755,-0.169515) , 
1, 2.33578, 1, 0, 0.507743,-0.00412627)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326084,-0.0113028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509246,0.00193296) , 
5, 82.7774, 1, 0, 0.40183,-0.0856626) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632318,0.00740786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.836599,0.0313955) , 
0, 0.0650465, 1, 0, 0.693834,0.136745) , 
7, 0.941862, 1, 0, 0.483872,-0.0231743)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469163,-0.000662556) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28953,-0.0116883) , 
4, -0.0143068, 1, 0, 0.355974,-0.111894) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680455,0.012883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.238141,-0.0139762) , 
1, 2.63782, 1, 0, 0.638477,0.100118) , 
6, 0.981404, 1, 0, 0.528768,0.0177843)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693834,0.0203492) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285042,-0.0121566) , 
8, 0.393997, 1, 0, 0.338781,-0.12928) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.236074,-0.0185969) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617696,0.00764775) , 
5, 33.4277, 1, 0, 0.59341,0.0607211) , 
7, 0.905633, 1, 0, 0.522719,0.00797247)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398162,-0.00684374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669345,0.0101607) , 
6, 0.986024, 1, 0, 0.535876,0.00781618) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.163281,-0.0171852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.353593,-0.0068908) , 
8, 0.911882, 1, 0, 0.236524,-0.206778) , 
1, 2.44785, 1, 0, 0.481907,-0.0308718)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266417,-0.0123193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59931,0.010609) , 
9, 0.79354, 1, 0, 0.341931,-0.1153) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.284477,-0.0173761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666983,0.0105852) , 
5, 34.1065, 1, 0, 0.63828,0.0827095) , 
3, 0.962228, 1, 0, 0.508675,-0.00388779)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640997,0.0135331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32071,-0.00982477) , 
8, 0.332083, 1, 0, 0.348392,-0.116529) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524307,-0.00247455) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.842315,0.0292681) , 
0, 0.0706377, 1, 0, 0.612532,0.0459798) , 
3, 0.966381, 1, 0, 0.473711,-0.0394283)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420485,-0.00172546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258758,-0.0143643) , 
6, 0.980945, 1, 0, 0.370092,-0.0835293) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558556,-0.000947531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.792034,0.0256385) , 
5, 95.189, 1, 0, 0.637356,0.0707299) , 
3, 0.963624, 1, 0, 0.515684,0.000503266)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371771,-0.00917304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.632438,0.00943357) , 
0, 0.182581, 1, 0, 0.408996,-0.093397) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609426,0.00616126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.9407,0.0507672) , 
2, 0.70308, 1, 0, 0.641709,0.0979695) , 
9, 0.773998, 1, 0, 0.467576,-0.0452246)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456929,-0.00467025) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656849,0.0116727) , 
5, 65.5857, 1, 0, 0.570872,0.0443594) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.158851,-0.0167191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.417128,-0.00319656) , 
9, 0.553376, 1, 0, 0.236315,-0.198365) , 
1, 2.44785, 1, 0, 0.513641,0.0028375)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.185917,-0.0151951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410409,-0.00418323) , 
3, 0.941728, 1, 0, 0.364458,-0.092825) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.732267,0.014174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497187,-0.000917548) , 
1, 2.18317, 1, 0, 0.626561,0.0689157) , 
6, 0.982347, 1, 0, 0.522776,0.0048714)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.205849,-0.0150153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460428,0.000346518) , 
5, 91.6716, 1, 0, 0.277225,-0.1672) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.65338,0.00735731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340398,-0.0092587) , 
1, 2.2924, 1, 0, 0.55025,0.00831966) , 
3, 0.954008, 1, 0, 0.474487,-0.0403859)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498415,-0.000485263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.754884,0.0144494) , 
7, 0.936811, 1, 0, 0.58787,0.041721) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.635948,0.0134117) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280567,-0.0111091) , 
4, -0.042194, 1, 0, 0.321042,-0.126931) , 
1, 2.30946, 1, 0, 0.508558,-0.00840938)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.368092,-0.00834528) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576002,0.000334291) , 
6, 0.991125, 1, 0, 0.450051,-0.0680042) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326878,-0.0084352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.695997,0.0150295) , 
3, 0.956456, 1, 0, 0.592604,0.0747503) , 
5, 79.8782, 1, 0, 0.513438,-0.00452761)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434935,-0.00282612) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187193,-0.0136875) , 
1, 2.33062, 1, 0, 0.360213,-0.0890665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568626,-0.00090737) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.81119,0.0265676) , 
5, 97.5371, 1, 0, 0.633559,0.0541374) , 
3, 0.966279, 1, 0, 0.493123,-0.0194362)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360468,-0.00633032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.745137,0.0156256) , 
3, 0.956049, 1, 0, 0.620433,0.0695362) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328121,-0.0100555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488585,-0.000220338) , 
5, 108.766, 1, 0, 0.376118,-0.0995988) , 
1, 2.15042, 1, 0, 0.494522,-0.0176303)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513987,-0.00261819) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.803117,0.0247801) , 
5, 97.6309, 1, 0, 0.582166,0.0266473) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.294218,-0.0102675) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.776528,0.026519) , 
3, 0.98744, 1, 0, 0.344727,-0.106663) , 
1, 2.26756, 1, 0, 0.503448,-0.0175488)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470667,-0.00394986) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.667266,0.0105299) , 
5, 103.681, 1, 0, 0.513481,-0.0150238) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25437,-0.0108388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0785848,-0.019282) , 
4, 0.0902769, 1, 0, 0.175746,-0.228389) , 
1, 2.5973, 1, 0, 0.474686,-0.0395322)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.279156,-0.0122152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.593647,0.00347149) , 
0, 0.110065, 1, 0, 0.396481,-0.0959757) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550046,0.00148411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.755175,0.0188569) , 
5, 94.818, 1, 0, 0.616037,0.0671341) , 
9, 0.668172, 1, 0, 0.498726,-0.0200169)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297361,-0.0109421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58599,0.00322097) , 
7, 0.900341, 1, 0, 0.527879,-0.00334888) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103467,-0.0177012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220744,-0.0133954) , 
9, 0.49491, 1, 0, 0.154373,-0.247881) , 
1, 2.59611, 1, 0, 0.487583,-0.0297306)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.279491,-0.0108368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.424287,-0.00267096) , 
5, 110.165, 1, 0, 0.310931,-0.130852) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55881,-0.00095869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.850743,0.0279529) , 
0, 0.0998266, 1, 0, 0.622724,0.0399304) , 
3, 0.966095, 1, 0, 0.468855,-0.0443504)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4037,-0.00921487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590659,0.00362418) , 
5, 44.3416, 1, 0, 0.557214,0.0110572) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.146526,-0.0160388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.353751,-0.00543508) , 
9, 0.441935, 1, 0, 0.298658,-0.120198) , 
1, 2.37747, 1, 0, 0.498668,-0.0186634)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.266286,-0.0102472) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531199,0.00479269) , 
9, 0.844533, 1, 0, 0.293324,-0.127665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396838,-0.0103168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656657,0.00832335) , 
5, 42.6021, 1, 0, 0.620738,0.054447) , 
3, 0.960292, 1, 0, 0.482493,-0.0224469)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.149197,-0.0214725) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.324103,-0.008239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.611743,0.0052726) , 
7, 0.905551, 1, 0, 0.530906,0.00855375) , 
5, 32.9639, 1, 0, 0.511227,-0.00983134)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.28592,-0.0114408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550778,0.000507092) , 
0, 0.128955, 1, 0, 0.381498,-0.101289) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515923,0.00100248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.860324,0.028179) , 
3, 0.974506, 1, 0, 0.622162,0.0753644) , 
9, 0.668931, 1, 0, 0.484833,-0.0254382)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.166872,-0.0136437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479717,-0.00344167) , 
3, 0.945248, 1, 0, 0.427134,-0.0694572) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744806,0.0169203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343121,-0.00577587) , 
1, 2.38982, 1, 0, 0.601721,0.0721779) , 
5, 92.4717, 1, 0, 0.479305,-0.027133)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424703,-0.00630933) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584642,0.00488145) , 
5, 63.3724, 1, 0, 0.522504,0.00137289) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0956413,-0.0169219) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.179432,-0.0110765) , 
0, -0.0824304, 1, 0, 0.133834,-0.214467) , 
1, 2.70722, 1, 0, 0.49172,-0.0157221)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.261761,-0.0125558) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.432536,-0.00267471) , 
2, 0.280803, 1, 0, 0.379229,-0.0796087) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.8702,0.0266294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59482,0.00216796) , 
1, 2.09815, 1, 0, 0.708855,0.0947608) , 
3, 0.971836, 1, 0, 0.492702,-0.0195824)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491775,-0.00357749) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.657363,0.00765519) , 
5, 64.9383, 1, 0, 0.583543,0.0237099) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.224946,-0.0109849) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484379,-0.00170521) , 
3, 0.972447, 1, 0, 0.323946,-0.106416) , 
1, 2.30946, 1, 0, 0.505775,-0.015272)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.389941,-0.0114283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72357,0.0143496) , 
1, 1.80567, 1, 0, 0.626394,0.0503499) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.221528,-0.0122156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467665,-0.00334241) , 
7, 0.900437, 1, 0, 0.414457,-0.0705562) , 
1, 2.03947, 1, 0, 0.485663,-0.0299346)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509605,-0.00136555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.793799,0.020971) , 
5, 97.1893, 1, 0, 0.579663,0.0312969) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316325,-0.00710952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139874,-0.0148162) , 
4, 0.0330481, 1, 0, 0.212466,-0.171326) , 
1, 2.42305, 1, 0, 0.499779,-0.0127842)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518632,0.000650395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263294,-0.0125961) , 
4, 0.0746319, 1, 0, 0.447053,-0.0445845) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524178,0.00396147) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.875783,0.0313866) , 
3, 0.968099, 1, 0, 0.696176,0.135646) , 
5, 94.818, 1, 0, 0.522999,0.0103595)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587946,0.00836365) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342423,-0.00692994) , 
4, -0.052537, 1, 0, 0.378092,-0.0665141) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.818595,0.0204523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.566389,0.000566367) , 
1, 2.03247, 1, 0, 0.647385,0.0567488) , 
6, 0.986486, 1, 0, 0.518204,-0.00238064)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446588,-0.00418058) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613742,0.00717775) , 
5, 103.356, 1, 0, 0.488414,-0.019924) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.922466,0.0429269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.782047,0.0112652) , 
5, 88.0688, 1, 0, 0.864093,0.215595) , 
7, 0.972872, 1, 0, 0.514158,-0.0037847)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505061,-0.00526184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601313,0.00310786) , 
1, 1.92887, 1, 0, 0.578404,0.0105408) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.193349,-0.0119986) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50321,0.00214654) , 
7, 0.941874, 1, 0, 0.27257,-0.12267) , 
1, 2.36461, 1, 0, 0.497784,-0.0245743)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387281,-0.00983706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.687678,0.00983732) , 
5, 46.2496, 1, 0, 0.621266,0.0452817) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.261083,-0.0107565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56097,0.00113323) , 
3, 0.972447, 1, 0, 0.362416,-0.0957531) , 
1, 2.17281, 1, 0, 0.500407,-0.0205684)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326638,-0.00939474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.568819,0.00202329) , 
0, 0.103768, 1, 0, 0.410346,-0.0749963) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.650049,0.00698594) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.936428,0.0453505) , 
9, 0.902953, 1, 0, 0.693834,0.106735) , 
9, 0.741389, 1, 0, 0.497573,-0.0190789)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506083,-0.000891538) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228416,-0.0163544) , 
4, 0.133997, 1, 0, 0.47601,-0.0351191) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425996,-0.00107055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.860735,0.0269275) , 
3, 0.965084, 1, 0, 0.618595,0.0814232) , 
0, 0.0834972, 1, 0, 0.516943,-0.0016624)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476537,0.00619941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341818,-0.00703246) , 
0, -0.0695312, 1, 0, 0.372256,-0.0584385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704176,0.00727215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.233755,-0.0109677) , 
1, 2.62664, 1, 0, 0.655008,0.0430956) , 
3, 0.96595, 1, 0, 0.512529,-0.00806766)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517353,-0.00135897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.754459,0.014441) , 
5, 93.3194, 1, 0, 0.585857,0.0249385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513987,0.00752911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.179135,-0.0124576) , 
4, -0.0247476, 1, 0, 0.232045,-0.134715) , 
1, 2.40233, 1, 0, 0.51517,-0.00695817)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.183093,-0.0125768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492771,-0.00324693) , 
3, 0.951421, 1, 0, 0.424819,-0.069942) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.728693,0.014677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531199,-0.0107042) , 
2, 0.678158, 1, 0, 0.706189,0.105709) , 
9, 0.796377, 1, 0, 0.488913,-0.02993)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.216404,-0.0153913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513987,-0.00205183) , 
9, 0.557221, 1, 0, 0.306383,-0.15821) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2556,-0.0149709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613685,0.00646748) , 
5, 34.632, 1, 0, 0.59115,0.0494274) , 
2, 0.263714, 1, 0, 0.515422,-0.00578918)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.175926,-0.0166175) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345227,-0.00555379) , 
1, 1.85198, 1, 0, 0.318732,-0.102055) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56864,-0.00229332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.867493,0.0261414) , 
0, 0.0998044, 1, 0, 0.635327,0.0226541) , 
3, 0.967621, 1, 0, 0.464505,-0.0446341)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.705618,0.0123376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51753,-0.00467033) , 
4, 0.0472402, 1, 0, 0.636071,0.0533573) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35215,-0.00743229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617417,0.00662023) , 
9, 0.745548, 1, 0, 0.395828,-0.0688589) , 
1, 2.11943, 1, 0, 0.50279,-0.0144453)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.198271,-0.0113567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486903,-0.0036251) , 
9, 0.542842, 1, 0, 0.425996,-0.0672914) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.344475,-0.00715593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.734448,0.0137615) , 
7, 0.900379, 1, 0, 0.644326,0.0698296) , 
0, 0.110065, 1, 0, 0.477123,-0.0351811)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581655,0.00522569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522748,-0.0125328) , 
7, 0.968029, 1, 0, 0.572227,0.0251747) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.310972,-0.0104859) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563409,0.00510907) , 
5, 100.324, 1, 0, 0.372312,-0.0929462) , 
4, 0.0485835, 1, 0, 0.499159,-0.0179981)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.17344,-0.0145046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.52179,-0.00100254) , 
3, 0.93713, 1, 0, 0.503321,-0.0225385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.185616,-0.0158275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546263,0.000989555) , 
0, 0.201612, 1, 0, 0.305048,-0.148052) , 
4, 0.126795, 1, 0, 0.474102,-0.0410348)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422531,-0.0060149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.719098,0.0171122) , 
2, 0.680964, 1, 0, 0.44384,-0.0572965) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712418,0.0146286) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469387,-0.00566683) , 
5, 133.999, 1, 0, 0.620738,0.0559989) , 
5, 97.1893, 1, 0, 0.496663,-0.0234656)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.382431,-0.0083428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550347,0.001633) , 
5, 53.0617, 1, 0, 0.515255,-0.00843618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.888039,0.0427745) , 
0, 0.258044, 1, 0, 0.524988,5.98937e-05)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311882,-0.0166523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.63412,0.00594337) , 
1, 1.62757, 1, 0, 0.616868,0.044851) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.282582,-0.00784156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.672171,0.0170901) , 
9, 0.725226, 1, 0, 0.321006,-0.0774868) , 
1, 2.25577, 1, 0, 0.514164,0.00238325)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551071,-0.000826959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.242553,-0.00895188) , 
1, 2.42496, 1, 0, 0.487953,-0.0322833) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.683372,0.00867939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.950648,0.0490694) , 
2, 0.721598, 1, 0, 0.81119,0.198829) , 
2, 0.677064, 1, 0, 0.509485,-0.0168881)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524661,9.03879e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.753126,0.0201231) , 
0, 0.143229, 1, 0, 0.549414,0.0198452) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627211,0.00643465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332861,-0.00949729) , 
8, 0.437326, 1, 0, 0.39041,-0.0865846) , 
4, 0.0833059, 1, 0, 0.51174,-0.00537247)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480051,-0.00239794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14065,-0.0175405) , 
1, 1.96852, 1, 0, 0.253153,-0.194694) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661673,0.0064974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376058,-0.0036237) , 
1, 2.22733, 1, 0, 0.549375,0.0206642) , 
5, 35.778, 1, 0, 0.524703,0.00272749)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.190578,-0.0130145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465123,-0.00160973) , 
9, 0.667318, 1, 0, 0.316325,-0.108802) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.424287,-0.00602023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.629206,0.0047505) , 
5, 44.9521, 1, 0, 0.596292,0.0274479) , 
7, 0.905597, 1, 0, 0.516894,-0.0111923)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318137,-0.0153453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.700755,0.00958737) , 
5, 71.6615, 1, 0, 0.388004,-0.15597) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684855,0.00780517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398601,-0.00442055) , 
1, 2.13762, 1, 0, 0.509567,-0.00522125) , 
1, 1.86224, 1, 0, 0.492619,-0.0262388)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.394281,-0.00258129) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320078,-0.0142746) , 
6, 0.990388, 1, 0, 0.375997,-0.0726541) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485663,-0.00969361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.726599,0.00954317) , 
9, 0.471518, 1, 0, 0.684353,0.0494869) , 
3, 0.972557, 1, 0, 0.490699,-0.0272203)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318409,-0.0157181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503657,-0.00139315) , 
1, 1.81324, 1, 0, 0.48721,-0.033115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.725569,0.0195519) , 
0, 0.23413, 1, 0, 0.49904,-0.0225591)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363943,-0.00836685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393556,-0.00164339) , 
8, 0.690323, 1, 0, 0.377644,-0.0688211) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656606,-0.0015329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.741054,0.0148986) , 
8, 0.682244, 1, 0, 0.691908,0.0466979) , 
3, 0.971836, 1, 0, 0.497031,-0.0249359)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.212466,-0.0195211) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.268252,-0.00864712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.580252,0.00258383) , 
6, 0.964694, 1, 0, 0.509636,-0.00548486) , 
1, 1.65559, 1, 0, 0.497303,-0.017333)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.294561,-0.00808983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508287,0.00544708) , 
0, 0.171541, 1, 0, 0.32031,-0.0878554) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420742,-0.0183266) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.673302,0.00457512) , 
1, 1.77564, 1, 0, 0.65466,0.0228677) , 
3, 0.966096, 1, 0, 0.48302,-0.0339724)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576002,0.00258859) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472786,-0.00346208) , 
4, 0.0066141, 1, 0, 0.521725,-0.00789495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0964465,-0.0134342) , 
1, 2.69114, 1, 0, 0.4893,-0.0205437)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558096,0.00282702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344999,-0.00688188) , 
8, 0.391016, 1, 0, 0.378309,-0.0703179) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.826985,0.0176074) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388462,-0.00434672) , 
1, 2.42552, 1, 0, 0.749497,0.0958617) , 
3, 0.974685, 1, 0, 0.491635,-0.0195824)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155411,-0.0150607) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347157,-0.004414) , 
7, 0.893007, 1, 0, 0.2927,-0.101978) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330618,-0.0108222) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.61446,0.00403157) , 
5, 35.5225, 1, 0, 0.591847,0.0255952) , 
7, 0.905633, 1, 0, 0.517037,-0.00630826)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523157,0.00662573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339718,-0.00996083) , 
0, -0.0928819, 1, 0, 0.373894,-0.0889878) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.282026,-0.0119131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.582576,0.00370675) , 
5, 35.0587, 1, 0, 0.558108,0.0217361) , 
2, 0.304559, 1, 0, 0.492537,-0.017676)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693834,0.0248004) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.287775,-0.0143924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452676,-0.00511837) , 
1, 1.81324, 1, 0, 0.437749,-0.0719497) , 
0, -0.142098, 1, 0, 0.44387,-0.0649519)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.294512,-0.0150884) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553628,0.00218892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344365,-0.00870006) , 
4, 0.118746, 1, 0, 0.519294,0.00227122) , 
1, 1.6134, 1, 0, 0.50956,-0.00681805)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.306169,-0.0105003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514329,-0.00131633) , 
2, 0.263486, 1, 0, 0.461713,-0.0450593) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410826,-0.0103655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.874379,0.0355902) , 
1, 1.91593, 1, 0, 0.669514,0.0857357) , 
0, 0.156967, 1, 0, 0.492419,-0.0257323)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330618,-0.0148331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.700371,0.0107236) , 
1, 1.63706, 1, 0, 0.663791,0.0686758) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616156,0.026261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454555,-0.00392548) , 
0, -0.133261, 1, 0, 0.462564,-0.0318896) , 
1, 2.03033, 1, 0, 0.526606,0.00011584)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.195933,-0.0160465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437638,-0.00581239) , 
5, 45.8436, 1, 0, 0.406935,-0.0897638) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.332317,-0.00523443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701701,0.00820598) , 
3, 0.963362, 1, 0, 0.533215,0.0090509) , 
0, -0.0185387, 1, 0, 0.474686,-0.0367476)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406381,-0.004871) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222716,-0.0158323) , 
4, 0.051905, 1, 0, 0.331258,-0.12639) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531849,0.001663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.898744,0.0375065) , 
2, 0.719712, 1, 0, 0.544688,0.0264366) , 
5, 41.7456, 1, 0, 0.514995,0.00517528)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.806002,0.0269014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468691,-0.00220796) , 
4, -0.0944972, 1, 0, 0.480652,-0.0164232) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.728131,0.0048545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.955613,0.0464922) , 
4, 0.0323356, 1, 0, 0.809492,0.12443) , 
7, 0.972769, 1, 0, 0.512791,-0.00265683)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.323808,-0.00973296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496897,-0.00103096) , 
5, 43.6477, 1, 0, 0.463457,-0.0338773) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396674,-0.0032489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.76872,0.0186016) , 
9, 0.480892, 1, 0, 0.683808,0.109569) , 
5, 96.3663, 1, 0, 0.532616,0.0111443)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311009,-0.0137463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.482853,-0.00261183) , 
1, 1.81967, 1, 0, 0.466158,-0.0438722) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.689343,0.0149823) , 
0, 0.25717, 1, 0, 0.475163,-0.0363007)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38211,-0.00276442) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.690855,0.00652938) , 
3, 0.966279, 1, 0, 0.536031,0.0116845) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.105151,-0.0133399) , 
1, 2.73236, 1, 0, 0.503843,-0.00238715)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.395883,-0.00412939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.662236,0.00389212) , 
7, 0.926327, 1, 0, 0.513926,-0.012687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0825087,-0.0142377) , 
1, 2.74789, 1, 0, 0.483084,-0.0249599)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471839,-0.00225457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270151,-0.0111866) , 
4, 0.0831231, 1, 0, 0.410864,-0.0632309) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.684719,0.0144944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53916,-0.00429266) , 
2, 0.438833, 1, 0, 0.620973,0.0534727) , 
5, 94.818, 1, 0, 0.475896,-0.0271095)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388356,-0.0068672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.753274,0.0130717) , 
7, 0.972784, 1, 0, 0.421178,-0.0666109) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537054,0.00141115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.932369,0.0431959) , 
0, 0.0994227, 1, 0, 0.614711,0.0646394) , 
5, 111.506, 1, 0, 0.463322,-0.0380296)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.284477,-0.0117764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499135,-0.000813137) , 
2, 0.279276, 1, 0, 0.42649,-0.0578731) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501794,-0.0128642) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.616156,0.00638515) , 
8, 0.318229, 1, 0, 0.602325,0.0375773) , 
5, 86.8861, 1, 0, 0.494751,-0.0208182)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435802,-0.0005441) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.76872,0.0134378) , 
3, 0.974432, 1, 0, 0.5221,0.0224873) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463322,-0.0256913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6538,0.00211854) , 
1, 2.1721, 1, 0, 0.539355,-0.151621) , 
3, 0.991773, 1, 0, 0.523294,0.0104352)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.274153,-0.016715) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423935,-0.00415661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.611585,0.00349429) , 
9, 0.739118, 1, 0, 0.482454,-0.0222467) , 
1, 1.60807, 1, 0, 0.475052,-0.0297732)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418475,0.00281521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333238,-0.00799756) , 
6, 0.976816, 1, 0, 0.377891,-0.0318204) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580043,-0.000535707) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.849974,0.0214377) , 
0, 0.0576533, 1, 0, 0.658757,0.0386389) , 
3, 0.966288, 1, 0, 0.524978,0.00507853)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.812858,0.0273271) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.643196,0.00526336) , 
9, 0.567371, 1, 0, 0.68687,0.0934544) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38182,-0.00576161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.697334,0.00964463) , 
9, 0.795871, 1, 0, 0.425384,-0.0463938) , 
1, 2.02594, 1, 0, 0.492745,-0.0103679)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.41769,-0.00463678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.691737,0.0103551) , 
0, 0.182213, 1, 0, 0.451523,-0.0364569) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764877,0.0133212) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30031,-0.00544646) , 
1, 2.42272, 1, 0, 0.614853,0.0505786) , 
5, 97.5371, 1, 0, 0.501109,-0.0100336)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.242695,-0.00396977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.67157,0.0131283) , 
9, 0.647111, 1, 0, 0.529856,0.0692378) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468162,-0.00418866) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.740914,0.0167424) , 
0, 0.249811, 1, 0, 0.483273,-0.0363507) , 
0, -0.0847461, 1, 0, 0.493188,-0.0138759)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.276887,-0.00810176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.599897,0.00207636) , 
0, 0.161925, 1, 0, 0.371026,-0.0650611) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38033,-0.0111167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608697,0.00462119) , 
1, 1.80438, 1, 0, 0.585648,0.0272234) , 
9, 0.599148, 1, 0, 0.49455,-0.0119476)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.226499,-0.0078058) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497856,0.00619808) , 
5, 101.269, 1, 0, 0.285348,-0.0651184) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551585,-0.000227462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.741105,0.0134902) , 
0, 0.0739546, 1, 0, 0.609923,0.0329538) , 
3, 0.95317, 1, 0, 0.53347,0.00985296)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.240853,-0.0193287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382498,-0.00735017) , 
8, 0.423164, 1, 0, 0.318963,-0.170572) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.420452,-0.00375679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.657867,0.00687962) , 
9, 0.66876, 1, 0, 0.52126,0.00291391) , 
1, 1.81967, 1, 0, 0.499392,-0.0158396)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.260897,-0.00696941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51622,-0.00157375) , 
6, 0.972106, 1, 0, 0.44555,-0.037479) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606277,-0.000353394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.713271,0.0123065) , 
2, 0.313854, 1, 0, 0.686938,0.0833775) , 
9, 0.806023, 1, 0, 0.494826,-0.0128077)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583834,0.00992609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.239898,-0.0134603) , 
8, 0.400456, 1, 0, 0.291157,-0.135804) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451017,-0.00229886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.696176,0.00968041) , 
9, 0.705049, 1, 0, 0.544141,0.0175804) , 
5, 44.9521, 1, 0, 0.499018,-0.00977759)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228152,-0.0168039) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311009,-0.00575354) , 
4, -0.0408088, 1, 0, 0.283362,-0.132451) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.429709,-0.00477351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6538,0.00376231) , 
9, 0.710606, 1, 0, 0.512924,-0.0212878) , 
5, 41.7456, 1, 0, 0.48097,-0.0367614)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311378,-0.00783649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.642675,0.00634922) , 
0, 0.184141, 1, 0, 0.384857,-0.0611167) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345884,-0.00603622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.642654,0.00561925) , 
7, 0.900398, 1, 0, 0.583186,0.0279983) , 
9, 0.598744, 1, 0, 0.501891,-0.00853012)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499551,0.00232112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569327,-0.00552727) , 
6, 0.990728, 1, 0, 0.532119,-0.012576) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.125787,-0.00972647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.111822,-0.0149314) , 
2, 0.305403, 1, 0, 0.12076,-0.148025) , 
1, 2.59715, 1, 0, 0.484769,-0.028167)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.33897,-0.00893579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385815,0.0014043) , 
8, 0.694724, 1, 0, 0.35899,-0.0601387) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.722371,0.0205333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.690297,0.0032513) , 
2, 0.182929, 1, 0, 0.693834,0.044003) , 
3, 0.968222, 1, 0, 0.509062,-0.013464)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327545,-0.00791046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649052,0.00675823) , 
0, 0.175646, 1, 0, 0.402431,-0.059337) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.365679,-0.00586996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692757,0.00829342) , 
6, 0.967966, 1, 0, 0.621433,0.0413021) , 
9, 0.668931, 1, 0, 0.498007,-0.0154164)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595312,0.000777172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.800145,0.0289007) , 
4, -0.0737318, 1, 0, 0.700988,0.121964) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49243,-0.00655892) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471819,0.000353613) , 
8, 0.543483, 1, 0, 0.479231,-0.0238251) , 
4, -0.0544431, 1, 0, 0.512028,-0.00226356)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.340354,-0.00734687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478425,0.00699232) , 
5, 108.607, 1, 0, 0.373522,-0.0485924) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.287181,-0.0135084) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590659,0.00445099) , 
1, 1.69152, 1, 0, 0.575773,0.0335311) , 
2, 0.279739, 1, 0, 0.506504,0.0054045)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.351774,-0.00412413) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.639846,0.00656384) , 
0, 0.175646, 1, 0, 0.414665,-0.0244389) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540765,-0.00506698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701625,0.0132125) , 
0, -0.0983158, 1, 0, 0.659367,0.0746475) , 
9, 0.669779, 1, 0, 0.524968,0.0202258)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520396,-0.000162739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30031,-0.0153973) , 
8, 1.11771, 1, 0, 0.509262,-0.0113263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.830798,0.0464515) , 
8, 1.23519, 1, 0, 0.51818,-0.00119139)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.767705,0.0318991) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210492,-0.011248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523921,-0.000393983) , 
6, 0.949093, 1, 0, 0.492702,-0.0192622) , 
1, 1.67511, 1, 0, 0.499815,-0.0117257)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.190979,-0.015796) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507272,-0.00116371) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.755175,0.0306152) , 
5, 155.57, 1, 0, 0.516895,-0.00300788) , 
5, 33.4277, 1, 0, 0.49768,-0.0165315)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.299749,-0.00190027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297497,-0.0183516) , 
3, 0.969401, 1, 0, 0.298571,-0.14065) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.847818,0.0248029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504724,-0.00194679) , 
8, 0.252711, 1, 0, 0.520789,-0.011646) , 
5, 41.7456, 1, 0, 0.490138,-0.02944)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495464,-0.00117558) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223465,-0.0195815) , 
9, 0.694269, 1, 0, 0.338503,-0.165348) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455207,-0.00224938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.737841,0.0098706) , 
9, 0.803479, 1, 0, 0.50838,-0.00446779) , 
1, 1.75999, 1, 0, 0.496593,-0.0156307)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484211,-0.000952234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463322,-0.0172346) , 
2, 0.694617, 1, 0, 0.482787,-0.0223185) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.923585,0.0399262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.725569,0.00351289) , 
7, 0.983581, 1, 0, 0.825852,0.142322) , 
7, 0.973197, 1, 0, 0.511113,-0.00872449)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.240853,-0.0127267) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562828,0.0052057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.552576,-0.0038138) , 
2, 0.535234, 1, 0, 0.560279,0.029716) , 
9, 0.361996, 1, 0, 0.542723,0.0195711)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645098,0.0257162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513987,0.000969742) , 
7, 0.91544, 1, 0, 0.560389,0.0886673) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433408,-0.00428458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.655637,0.00755818) , 
0, 0.114702, 1, 0, 0.497712,-0.0141417) , 
0, -0.0803274, 1, 0, 0.510607,0.00701095)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.358386,-0.00189744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.158851,-0.0192402) , 
3, 0.958808, 1, 0, 0.3356,-0.0526401) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.717585,0.017984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626625,0.000388766) , 
7, 0.921958, 1, 0, 0.64621,0.0377993) , 
3, 0.960881, 1, 0, 0.51933,0.000855987)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543161,0.00271895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540816,-0.00331596) , 
2, 0.485653, 1, 0, 0.542236,0.00358404) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298203,-0.0103647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587397,0.00643672) , 
5, 100.301, 1, 0, 0.360826,-0.086635) , 
4, 0.087644, 1, 0, 0.502174,-0.0163394)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.787868,0.019964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486846,-0.00240926) , 
4, -0.0850349, 1, 0, 0.500962,-0.0172011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.731142,0.035046) , 
8, 1.25217, 1, 0, 0.507846,-0.00755963)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433714,0.00106621) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537013,-0.0054213) , 
7, 0.921293, 1, 0, 0.490008,-0.025476) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.334929,-0.00788241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.790664,0.0218396) , 
7, 0.904556, 1, 0, 0.653799,0.0850998) , 
0, 0.186065, 1, 0, 0.509412,-0.0123763)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647657,0.00556095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.962524,0.0512723) , 
2, 0.479779, 1, 0, 0.768972,0.151564) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416844,-0.00186977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.712734,0.00938196) , 
7, 0.936607, 1, 0, 0.521861,0.0141593) , 
8, 0.355118, 1, 0, 0.54868,0.0290717)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.184752,-0.0184615) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510089,9.7283e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439376,-0.0135096) , 
5, 128.624, 1, 0, 0.501793,-0.0176279) , 
1, 1.6134, 1, 0, 0.489501,-0.0271109)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.697019,0.0327577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511542,0.00208239) , 
2, 0.295226, 1, 0, 0.594323,0.133127) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402534,-0.0072832) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527164,-0.000761405) , 
0, -0.0254037, 1, 0, 0.484034,-0.0344273) , 
0, -0.109049, 1, 0, 0.498547,-0.0123799)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361655,0.00432378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224651,-0.0112385) , 
6, 0.94437, 1, 0, 0.247453,-0.111891) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490854,-0.00297998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.68719,0.00881865) , 
5, 99.5254, 1, 0, 0.550906,-0.000248943) , 
7, 0.900521, 1, 0, 0.496074,-0.020422)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.23348,-0.0129536) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.216441,-0.0089247) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57628,0.0019694) , 
3, 0.944918, 1, 0, 0.52694,0.00117646) , 
5, 35.0587, 1, 0, 0.509067,-0.0098753)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595638,0.0225005) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455697,-0.0030142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.708695,0.00810509) , 
9, 0.80412, 1, 0, 0.502896,-0.0138812) , 
9, 0.354597, 1, 0, 0.506423,-0.00673102)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374228,-0.00994685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588749,0.00190038) , 
1, 1.81986, 1, 0, 0.564541,0.00336264) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364127,0.00378362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216723,-0.00897968) , 
0, -0.0966148, 1, 0, 0.262048,-0.0666588) , 
1, 2.39199, 1, 0, 0.492784,-0.0132478)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452077,-0.00127132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377365,-0.0163851) , 
2, 0.533732, 1, 0, 0.432003,-0.0636502) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585666,0.00480172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40804,-0.00813358) , 
4, 0.0966364, 1, 0, 0.554584,0.024162) , 
0, -0.0361411, 1, 0, 0.505597,-0.0109306)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721235,0.0155497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.521636,-0.00137986) , 
0, -0.0108412, 1, 0, 0.592755,0.0396684) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455267,-0.00100626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436764,-0.00854521) , 
2, 0.369252, 1, 0, 0.447188,-0.0494933) , 
4, -0.0263373, 1, 0, 0.491542,-0.0223256)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.840962,0.0299767) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471004,-0.00112836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.86292,0.0274299) , 
9, 0.914773, 1, 0, 0.484172,-0.00530035) , 
4, -0.0957156, 1, 0, 0.494213,0.00110508)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546016,0.00142128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37133,-0.00592693) , 
4, 0.087644, 1, 0, 0.504392,-0.00495861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.9407,0.0423228) , 
7, 0.988801, 1, 0, 0.515811,0.00148371)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219833,-0.00900308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.537472,-0.00118313) , 
6, 0.958278, 1, 0, 0.493911,-0.0262244) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.698196,0.0152111) , 
5, 146.763, 1, 0, 0.502711,-0.0189578)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.23851,-0.0125104) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461751,-0.00331316) , 
7, 0.900512, 1, 0, 0.420799,-0.0600584) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539355,-0.00931723) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584682,0.00590265) , 
4, -0.0753557, 1, 0, 0.579234,0.0393629) , 
0, -0.0173264, 1, 0, 0.508212,-0.00520491)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32273,-0.0038838) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.638595,0.00275043) , 
3, 0.962134, 1, 0, 0.498395,-0.00698134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.828051,0.0293998) , 
0, 0.258044, 1, 0, 0.511274,0.00200675)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.34645,-0.00827228) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459671,-0.0006671) , 
0, -0.0975555, 1, 0, 0.43892,-0.0244881) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.795288,0.0182053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.718268,0.00451695) , 
6, 0.994526, 1, 0, 0.747214,0.0746085) , 
7, 0.947207, 1, 0, 0.5242,0.00292408)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514788,-0.00474309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.212466,-0.0191548) , 
8, 0.695612, 1, 0, 0.494302,-0.0643058) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396884,-0.00306786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.639392,0.011415) , 
9, 0.566388, 1, 0, 0.489762,0.0209013) , 
8, 0.727211, 1, 0, 0.492493,-0.0303543)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412555,-0.0127181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.672171,0.018813) , 
0, 0.230875, 1, 0, 0.455099,-0.0960866) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528934,-0.000293937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.119697,-0.0111427) , 
1, 2.67081, 1, 0, 0.484739,-0.0164628) , 
1, 1.92924, 1, 0, 0.478854,-0.0322722)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.403737,-0.00474792) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.635052,0.00534928) , 
0, 0.175646, 1, 0, 0.436729,-0.0393399) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.900644,0.0368886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.625212,0.00258789) , 
4, -0.0413566, 1, 0, 0.672932,0.0614147) , 
9, 0.809304, 1, 0, 0.478684,-0.0214438)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.169005,-0.0158288) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56387,0.0102665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511927,-0.000916356) , 
0, -0.117143, 1, 0, 0.516708,0.00068119) , 
5, 32.9639, 1, 0, 0.500685,-0.0100087)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425002,-0.00466351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399951,-0.0195491) , 
3, 0.986249, 1, 0, 0.421623,-0.0745581) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439313,-0.00238864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.849023,0.0197578) , 
7, 0.941419, 1, 0, 0.546781,0.0135501) , 
0, 0.0530954, 1, 0, 0.465558,-0.0436288)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.197642,-0.014524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508287,-0.00333216) , 
5, 32.9639, 1, 0, 0.486833,-0.0467968) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.86859,0.0355783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451511,0.0010182) , 
1, 2.04009, 1, 0, 0.503595,0.0401896) , 
8, 0.727812, 1, 0, 0.493035,-0.0146134)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.248396,-0.0154302) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.256686,-0.00630569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.596023,0.00306869) , 
3, 0.95346, 1, 0, 0.518275,0.00510296) , 
1, 1.60807, 1, 0, 0.509267,-0.00224657)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.317793,-0.00653797) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549396,0.00546327) , 
2, 0.246921, 1, 0, 0.489651,0.0223635) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548461,-0.000244571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438754,-0.0144175) , 
2, 0.517848, 1, 0, 0.517503,-0.0484382) , 
5, 81.6602, 1, 0, 0.501998,-0.00902359)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.205357,-0.0147091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504568,0.000475972) , 
5, 32.8702, 1, 0, 0.48954,-0.00575001) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.884791,0.0503476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.682287,0.00888445) , 
2, 0.229689, 1, 0, 0.721003,0.121548) , 
5, 107.02, 1, 0, 0.541032,0.0225691)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.225922,-0.0165924) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486342,-0.000792323) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37984,-0.014221) , 
5, 135.724, 1, 0, 0.476288,-0.0233249) , 
1, 1.67511, 1, 0, 0.465514,-0.0323205)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397711,0.00189928) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926756,0.045117) , 
3, 0.966915, 1, 0, 0.450944,0.0501542) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712316,0.00238107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452289,-0.0084752) , 
1, 1.98169, 1, 0, 0.515218,-0.0679031) , 
7, 0.916019, 1, 0, 0.488757,-0.0193005)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435031,-0.00227098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.635399,0.00840481) , 
5, 97.7718, 1, 0, 0.500741,0.00754157) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489477,-0.00601943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34074,-0.0225973) , 
5, 115.247, 1, 0, 0.462024,-0.105726) , 
2, 0.53519, 1, 0, 0.491188,-0.0204047)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.236474,-0.0131715) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488279,-0.00179335) , 
5, 64.607, 1, 0, 0.395051,-0.0746056) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552576,-0.00414166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587248,0.00594208) , 
4, -0.0405006, 1, 0, 0.576705,0.0276162) , 
2, 0.261726, 1, 0, 0.526495,-0.000638543)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.198848,-0.0107758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502747,-0.0011743) , 
5, 35.778, 1, 0, 0.476416,-0.0238253) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601721,0.00307159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.814172,0.0294283) , 
2, 0.473167, 1, 0, 0.641862,0.0650102) , 
0, 0.130148, 1, 0, 0.512852,-0.00426129)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.14593,-0.0121868) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.552545,0.00385139) , 
6, 0.953638, 1, 0, 0.510931,0.0181377) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557326,0.00224891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461372,-0.0121865) , 
5, 63.1423, 1, 0, 0.49426,-0.0815608) , 
2, 0.541461, 1, 0, 0.506802,-0.00655459)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
